### ISSUE TITLE
Git conflict-lines hit source code !

### ISSUE THREAD

**Issue by socketpair** [greearb/hostap-ct#2]
Your version does not compile! see here:
https://github.com/greearb/hostap-ct/blob/db0466cdbfb697fc16687a68ae096d384bf0aa4f/src/rsn_supp/wpa.h#L403

**Comment by socketpair** [comment]
@klukonin

**Comment by klukonin** [comment]
That's why I can't compile this version of wpa_supplicant.

Thank you, @socketpair

**Comment by greearb** [comment]
I rebased against the latest upsteam repo just now and tried to fix this merge problem.  This code is only compiled when WPA is disabled, which is why I did not notice the problem in my build systems. Please re-clone (or:  git reset --hard HEAD~100; git pull) to get the latest code and see if this compiles better for you.
